---
# FIXME: adapt for Windows
#- name: Get Virtual Machine type
#  command: virt-what
#  register: virt_what
#  tags: ['configure-client']

#- set_fact:
#    vm_type: "{{ virt_what.stdout }}"
#  when: virt_what.stdout != ""
#  tags: ['configure-client']

- name: Setup Icinga constants
  win_lineinfile:
    path: "{{ win_config_root_dir }}/{{ constants_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^(\/\/)?const NodeName', line: 'const NodeName = "{{ inventory_hostname }}"' }
    - { regexp: '^(\/\/)?const ZoneName', line: 'const ZoneName = "{{ inventory_hostname }}"' }
    - { regexp: '^(\/\/)?const {{ plugins_custom_dir_var_name }} =(.+)', line: 'const {{ plugins_custom_dir_var_name }} = "{{ win_plugin_dest_dir }}"' }
  tags: ['configure-client']

- name: Setup Icinga zones
  win_template:
    src: ../templates/client-zones.conf.j2
    dest: "{{ win_config_root_dir }}/zones.conf"
  tags: ['configure-client']
    
- name: Copy CA and certs to client node
  win_copy:
    src: "{{ item }}"
    dest: "{{ win_client_certs_dir }}"\
  with_fileglob:
    - "/tmp/ansible/{{ inventory_hostname }}/icinga/*"
  when: icinga2_client_configured == False
  tags: ['configure-client']
      
- name: Configure Icinga API on satellite
  win_template:
    src: client-api.conf.j2
    dest: "{{ win_config_root_dir }}/features-available/api.conf"
    owner: root
    group: root
    mode: 0644
  tags: ['configure-client']

- name: Enable Icinga API on satellite
  win_lineinfile:
    path: "{{ win_config_root_dir }}/features-enabled/api.conf"
    regexp: '^(\/\/)?include "../features-available/api.conf"'
    line: 'include "../features-available/api.conf"'
  tags: ['configure-client']

- name: Disable Icinga notifier on satellite
  win_file:
    path: "{{ win_config_root_dir }}/features-enabled/notification.conf"
    state: absent
  tags: ['configure-client']

- name: Configure Icinga checker on satellite
  win_template:
    src: client-checker.conf.j2
    dest: "{{ win_config_root_dir }}/features-available/checker.conf"
    owner: root
    group: root
    mode: 0644
  tags: ['configure-client']
