---
- name: Ensure custom conf.d directory is present
  file:
    path: "{{ config_root_dir }}/{{ custom_confd_dir }}"
    state: directory
  tags: ['install-icinga2-stack', 'config']

- name: Ensure config files are recursively included from conf.d dir
  lineinfile:
    path: "{{ config_root_dir }}/{{ main_config_file }}"
    line: "include_recursive \"{{ custom_confd_dir }}\""
    state: present
  tags: ['install-icinga2-stack', 'config']


# Deploy services configurations

- name: Ensure services.d directory is present
  file:
    path: "{{ config_root_dir }}/{{ services_dir }}"
    state: directory
  tags: ['install-icinga2-stack', 'config']
  
- name: Ensure config files are recursively included from services dir
  lineinfile:
    path: "{{ config_root_dir }}/{{ main_config_file }}"
    line: "include_recursive \"{{ services_dir }}\""
    state: present
  tags: ['install-icinga2-stack', 'config']
  
- name: Remove default unnecessary config files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ default_unnecessary_config_files }}"
  tags: ['install-icinga2-stack', 'config']


# Reload Icinga2

- name: Reload Icinga2
  service:
    name: icinga2
    state: reloaded
  tags: ['install-icinga2-stack', 'config']
