---
- include_tasks: config-Linux.yml
  when: ansible_system == "Linux"
  tags: ['install-icinga2-stack', 'config']

- include_tasks: config-Windows.yml
  when: ansible_os_family == "Windows"
  tags: ['install-icinga2-stack', 'config']
