---
- name: Ensure custom conf.d directory is present
  file:
    path: "{{ config_root_dir }}/{{ confd_dir }}"
    state: directory
  tags: ['config']

- name: Ensure config files are recursively included from conf.d dir
  lineinfile:
    path: "{{ main_config_file }}"
    line: "include_recursive \"{{ confd_dir }}\""
    state: present
  tags: ['config']

- name: Ensure services.d directory is present
  file:
    path: "{{ config_root_dir }}/{{ services_dir }}"
    state: directory
  tags: ['config']

- name: Deploy services configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ config_root_dir }}/{{ services_dir }}/{{ item.dest }}"
  with_items: "{{ services_config_files }}"
  tags: ['config']
