---
- name: Configure Nginx for Icinga Web 2
  template:
    src: nginx-icingaweb2.conf.j2
    dest: "{{ icingaweb2_http_conf_file_path }}"
  when: icingaweb2_http_server|lower == 'nginx'
  tags: ['install-icinga2-stack', 'install-icingaweb2']
  debugger: on_skipped
  notify: Restart Nginx

- name: Set PHP Date Timezone
  lineinfile:
    dest: "{{ icingaweb2_php_ini_file_path }}"
    regexp: "date.timezone ="
    line: "date.timezone = {{ icingaweb2_timezone }}"
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']
  notify: "Restart PHP-FPM"

- name: Drop tables from Icingaweb2 Database
  shell: '{{ _mysql_cmd }} -Nse "SHOW TABLES;" {{ icingaweb2_db_name }} | while read table; do {{ _mysql_cmd }} -e "DROP TABLE $table" {{ icingaweb2_db_name }}; done'
  when: icingaweb2_install == true and icingaweb2_db_create == true and (icingaweb2_db_purge == true or icingaweb2_db_purge|bool == true)
  tags: ['install-icinga2-stack', 'install-icingaweb2']

- name: Get tables in Icinga2 IDO Database
  shell: '{{ _mysql_cmd }} -Nse "SHOW TABLES;" {{ icingaweb2_db_name }}'
  register: icingaweb2_db_tables
  when: icingaweb2_install == true and icingaweb2_db_create == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']

- name: Check if Icingaweb2 Database Schema file exists
  stat:
    path: "{{ icingaweb2_db_schema_file_path}}"
  register: icingaweb2_db_schema_file
  when: icingaweb2_install == true and icingaweb2_db_create == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']
  
- name: Import Icinga2 IDO Database Schema
  mysql_db:
    name: "{{ icinga2_ido_db_name }}"
    login_host: "{{ icingaweb2_db_host }}"
    login_user: "{{ icingaweb2_db_user }}"
    login_password: "{{ icingaweb2_db_password }}"
    state: import
    target: "{{ icingaweb2_db_schema_file_path }}"
  when: icingaweb2_install == true and icingaweb2_db_create == true and icingaweb2_db_schema_file is defined and icingaweb2_db_schema_file.stat is defined and icingaweb2_db_schema_file.stat.exists and icingaweb2_db_tables.stdout_lines == []
  tags: ['install-icinga2-stack', 'install-icingaweb2']
