---
# Nginx and PHP configuration

- name: Configure Nginx for Icinga Web 2
  template:
    src: nginx-icingaweb2.conf.j2
    dest: "{{ icingaweb2_http_conf_file_path }}"
  when: icingaweb2_http_server|lower == 'nginx'
  tags: ['install-icinga2-stack', 'install-icingaweb2']
  debugger: on_skipped
  notify: Restart Nginx

- name: Set PHP Date Timezone
  lineinfile:
    dest: "{{ icingaweb2_php_ini_file_path }}"
    regexp: "date.timezone ="
    line: "date.timezone = {{ icingaweb2_timezone }}"
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']
  notify: "Restart PHP-FPM"


# Icingaweb2 configuration

- name: Configure authentication configuration file
  template:
    src: templates/icingaweb2/authentication.ini.j2
    dest: /etc/icingaweb2/authentication.ini
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']

- name: Configure main configuration file
  template:
    src: templates/icingaweb2/config.ini.j2
    dest: /etc/icingaweb2/config.ini
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']

- name: Configure groups configuration file
  template:
    src: templates/icingaweb2/groups.ini.j2
    dest: /etc/icingaweb2/groups.ini
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']

- name: Configure resources configuration file
  template:
    src: templates/icingaweb2/resources.ini.j2
    dest: /etc/icingaweb2/resources.ini
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']

- name: Configure roles configuration file
  template:
    src: templates/icingaweb2/roles.ini.j2
    dest: /etc/icingaweb2/roles.ini
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']


# Configure root user

- name: Generate the password hash for the Icingaweb2 admin user
  command: "php -r \"echo password_hash('{{ icingaweb2_admin_password }}', PASSWORD_DEFAULT);\""
  register: icingaweb2_admin_password_hash
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']

- name: Configure the Icingaweb2 admin user
  shell: "{{ _mysql_cmd }} -Nse \"INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('{{ icingaweb2_admin_username }}', 1, '{{ icingaweb2_admin_password_hash.stdout_lines }}');\" {{ icingaweb2_db_name }}'"
  when: icingaweb2_install == true and icingaweb2_db_create == true and (icingaweb2_db_purge == true or icingaweb2_db_purge|bool == true)
  tags: ['install-icinga2-stack', 'install-icingaweb2']

# End

- name: Ensure that no setup token are configured
  file:
    path: /etc/icingaweb2/setup.token
    state: absent
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']
