---
- name: Configure Nginx for Icinga Web 2
  template:
    src: nginx-icingaweb2.conf.j2
    dest: "{{ icingaweb2_http_conf_file_path }}"
  when: icingaweb2_http_server|lower == 'nginx'
  tags: ['install-icinga2-stack', 'install-icingaweb2']
  debugger: on_skipped
  notify: Restart Nginx

- name: Set PHP Date Timezone
  lineinfile:
    dest: "{{ icingaweb2_php_ini_file_path }}"
    regexp: "date.timezone ="
    line: "date.timezone = {{ icingaweb2_timezone }}"
  when: icingaweb2_install == true
  tags: ['install-icinga2-stack', 'install-icingaweb2']
  notify: "Restart PHP-FPM"
