---
- import_tasks: vars.yml
  tags: ['always']

- include_tasks: install.yml
  tags: ['install']

- import_tasks: ido-install.yml
  when: icinga2_ido_enable == true
  tags: ['install', 'ido']  

- import_tasks: configure.yml
  when: icinga2_client_configure == false
  tags: ['install']
  
- import_tasks: node-configure.yml
  when: icinga2_master_setup == true
  tags: ['install']

- import_tasks: config.yml
  when: icinga2_client_configure == false
  tags: ['install', 'config']
