---
- name: Set Node Name
  lineinfile:
    dest: "{{ config_root_dir }}/constants.conf"
    regexp: "const NodeName ="
    line: "const NodeName = {{ icinga2_master_host }}"
  when: icinga2_master_setup == true
  tags: ['install-icinga2-stack']

- name: Copy zones configuration file
  template:
    src: templates/zones.conf.j2
    dest: "{{ config_root_dir }}/zones.conf"
  when: icinga2_master_setup == true
  tags: ['install-icinga2-stack']

- name: Check if CA certificate is already present
  stat:
    path: /var/lib/icinga2/certs/ca.crt
  register: icinga2_ca_file
  when: icinga2_master_setup == true
  tags: ['install-icinga2-stack']

- name: Create a new CA if not already exists
  command: icinga2 pki new-ca
  when: icinga2_master_setup == true and icinga2_ca_file.stat.exists == false
  tags: ['install-icinga2-stack']

#- name: Ensure zone directory exists
#  file:
#    path: "{{ config_root_dir }}/zones.d/{{   
